name       : python-marshmallow
version    : 3.17.1
release    : 4
source     :
    - https://github.com/marshmallow-code/marshmallow/archive/refs/tags/3.17.1.tar.gz : e3eb724a2199b2c20bb8ed35796520729e9b7ae71243e4ea046489785ec4ef56
homepage   : https://github.com/marshmallow-code/marshmallow
license    : MIT
component  : programming.python
summary    : A lightweight library for converting complex datatypes to and from native Python datatypes
description: |
    marshmallow is an ORM/ODM/framework-agnostic library for converting complex datatypes, such as objects, to and from native Python datatypes.  
builddeps  :
    - python-pytest     # check
    - python-pytz       # check
    - python-simplejson # check
rundeps    :
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
