name       : python-marshmallow
version    : 3.19.0
release    : 5
source     :
    - https://github.com/marshmallow-code/marshmallow/archive/refs/tags/3.19.0.tar.gz : a982b9a5f452eab26c4b5e5cc93f0b77d8f2a2eb8973ac06b866640699d35d24
homepage   : https://github.com/marshmallow-code/marshmallow
license    : MIT
component  : programming.python
summary    : A lightweight library for converting complex datatypes to and from native Python datatypes
description: |
    marshmallow is an ORM/ODM/framework-agnostic library for converting complex datatypes, such as objects, to and from native Python datatypes.  
builddeps  :
    - python-pytest     # check
    - python-pytz       # check
    - python-simplejson # check
rundeps    :
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
